export enum ModuleName {
  MODERATION = 'MODERATION',
  PROTECTION = 'PROTECTION',
  TICKETS = 'TICKETS',
  LOGS = 'LOGS',
  LEVELS = 'LEVELS',
  ECONOMY = 'ECONOMY',
  MUSIC = 'MUSIC',
  GIVEAWAYS = 'GIVEAWAYS',
  POLLS = 'POLLS',
  SUGGESTIONS = 'SUGGESTIONS',
  WELCOME = 'WELCOME',
  AUTOROLES = 'AUTOROLES',
  EMBEDS = 'EMBEDS',
}

export enum PermissionLevel {
  EVERYONE = 0,
  MODERATOR = 1,
  ADMIN = 2,
  GUILD_OWNER = 3,
  OWNER = 4,
}

export enum TicketStatus {
  OPEN = 'OPEN',
  CLAIMED = 'CLAIMED',
  PENDING = 'PENDING',
  CLOSED = 'CLOSED',
  DELETED = 'DELETED',
}

export enum LogEventType {
  MESSAGE_DELETE = 'MESSAGE_DELETE',
  MESSAGE_EDIT = 'MESSAGE_EDIT',
  MEMBER_JOIN = 'MEMBER_JOIN',
  MEMBER_LEAVE = 'MEMBER_LEAVE',
  MEMBER_BAN = 'MEMBER_BAN',
  MEMBER_UNBAN = 'MEMBER_UNBAN',
  MEMBER_KICK = 'MEMBER_KICK',
  MEMBER_MUTE = 'MEMBER_MUTE',
  MEMBER_UNMUTE = 'MEMBER_UNMUTE',
  MEMBER_ROLE_ADD = 'MEMBER_ROLE_ADD',
  MEMBER_ROLE_REMOVE = 'MEMBER_ROLE_REMOVE',
  CHANNEL_CREATE = 'CHANNEL_CREATE',
  CHANNEL_DELETE = 'CHANNEL_DELETE',
  CHANNEL_UPDATE = 'CHANNEL_UPDATE',
  INVITE_CREATE = 'INVITE_CREATE',
  VOICE_STATE_UPDATE = 'VOICE_STATE_UPDATE',
  TICKET_CREATE = 'TICKET_CREATE',
  TICKET_CLOSE = 'TICKET_CLOSE',
  AUTOMOD_ACTION = 'AUTOMOD_ACTION',
}

export enum ModerationCaseType {
  WARN = 'WARN',
  MUTE = 'MUTE',
  UNMUTE = 'UNMUTE',
  KICK = 'KICK',
  BAN = 'BAN',
  TEMPBAN = 'TEMPBAN',
  UNBAN = 'UNBAN',
  TIMEOUT = 'TIMEOUT',
}

export enum PremiumPlanTier {
  FREE = 'FREE',
  BASIC = 'BASIC',
  PRO = 'PRO',
  ENTERPRISE = 'ENTERPRISE',
}

export enum DeploymentStatus {
  PENDING = 'PENDING',
  RUNNING = 'RUNNING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  ROLLED_BACK = 'ROLLED_BACK',
}

export enum ThemeName {
  OLED = 'OLED',
  DARK = 'DARK',
  LIGHT = 'LIGHT',
  CATPPUCCIN = 'CATPPUCCIN',
  NORD = 'NORD',
  DRACULA = 'DRACULA',
  GRUVBOX = 'GRUVBOX',
  TOKYO_NIGHT = 'TOKYO_NIGHT',
  ROSE_PINE = 'ROSE_PINE',
  MONOKAI = 'MONOKAI',
}

export enum AuditAction {
  BLACKLIST_USER = 'BLACKLIST_USER',
  UNBLACKLIST_USER = 'UNBLACKLIST_USER',
  BLACKLIST_GUILD = 'BLACKLIST_GUILD',
  UNBLACKLIST_GUILD = 'UNBLACKLIST_GUILD',
  FORCE_LEAVE = 'FORCE_LEAVE',
  DEPLOYMENT_START = 'DEPLOYMENT_START',
  DEPLOYMENT_SUCCESS = 'DEPLOYMENT_SUCCESS',
  DEPLOYMENT_FAILURE = 'DEPLOYMENT_FAILURE',
  DEPLOYMENT_ROLLBACK = 'DEPLOYMENT_ROLLBACK',
  PREMIUM_GRANT = 'PREMIUM_GRANT',
  PREMIUM_REVOKE = 'PREMIUM_REVOKE',
  ALPHA_MODE_TOGGLE = 'ALPHA_MODE_TOGGLE',
  CHANGELOG_PUBLISH = 'CHANGELOG_PUBLISH',
  GLOBAL_ANNOUNCEMENT = 'GLOBAL_ANNOUNCEMENT',
  SERVICE_RESTART = 'SERVICE_RESTART',
  BACKUP_CREATED = 'BACKUP_CREATED',
  BACKUP_RESTORED = 'BACKUP_RESTORED',
  SETTINGS_CHANGE = 'SETTINGS_CHANGE',
  OWNER_LOGIN = 'OWNER_LOGIN',
  OWNER_LOGOUT = 'OWNER_LOGOUT',
}
